### ISSUE TITLE
error: could not open '/ffmpeg_sources/libfreetype2/freetype2/include/freetype/ttnameid.h' for writing

### ISSUE THREAD

**Issue by Kaos-Industries** [servo/libfreetype2#31]
I'm trying to build the package from source for FFmpeg, on a Cygwin/MinGW-w64 toolchain, but am running into the following fatal error during `make`:

> could not open '/ffmpeg_sources/libfreetype2/freetype2/include/freetype/ttnameid.h' for writing
> make: *** [/ffmpeg_sources/libfreetype2/freetype2/builds/exports.mk:68: /ffmpeg_sources/libfreetype2/freetype2/objs/ftexport.sym] Error 3

I've checked that that file exists where it does, and searching the web for the error doesn't give anything. 

This is the command I'm running to configure and make:

```
git clone --depth 1 https://github.com/servo/libfreetype2.git &&
cd libfreetype2/freetype2 &&
./autogen.sh && 
./configure --host=x86_64-w64-mingw32 --prefix="/usr/x86_64-w64-mingw32/sys-root/mingw" --enable-static --disable-shared 2>&1 | tee "/build_libfreetype.txt" &&
make -j$(nproc) 2>&1 | tee -a "/build_libfreetype.txt" &&
make install 2>&1 | tee -a "/build_libfreetype.txt"
```

Any idea what's going on here and how I can solve this?

Thanks.

**Comment by jdm** [comment]
This is a Rust crate. Any build that involves anything other than `cargo build` is unsupported.

**Comment by Kaos-Industries** [comment]
My bad. It was the only Github link I could fine for freetype2, but I've since found that the project is maintained [here](https://git.savannah.gnu.org/git/freetype/freetype2.git). I'll file a bug report there.
